routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\BusinessController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ArchingController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommandController;
use App\Http\Controllers\PrinterController;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\TableController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\FixedController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\RetirementController;
use App\Http\Controllers\NotificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () 
{
    return view('welcome');
});

Route::get('show/tables/{id}' 		, function($id)
{
	$room = App\Models\Room::find($id);
    
    if($room != null)
    	return view('table.parts.show_tables', compact('room'));
});

Route::get('consult/tables' 		, function()
{
	return Auth::user()->business->fixeds->where('status','occupied')->count();
});

Route::get('show/tabs/{id}'			, function($id)
{
	$room = App\Models\Room::find($id);
    return view('table.parts.tabs', compact('room'));
});

Route::get('show/commands/{id}'			, function($id)
{
	$fixed 		= App\Models\Fixed::find($id);
	$table      = $fixed->tables->where('status', 'enabled')->first();
    
    return view('table.parts.command_list', compact('table'));
});

Auth::routes();

Route::get('business/check/{id}'			, [BusinessController::class, 'check']);

Route::get('/home'							, [HomeController::class, 'index'])->middleware('waiter');
Route::get('/admin'							, [HomeController::class, 'admin'])->middleware('waiter');

Route::resource('business' 					, BusinessController::class)->middleware('admin');
Route::resource('category'	 				, CategoryController::class)->middleware('cashier');
Route::resource('reservation' 				, ReservationController::class)->middleware('waiter');
Route::resource('setting' 					, SettingController::class)->middleware('cashier');
Route::resource('supplier' 					, SupplierController::class)->middleware('cashier');
Route::resource('ticket' 					, TicketController::class)->middleware('waiter');
Route::resource('room' 						, RoomController::class)->middleware('waiter');
Route::resource('delivery'					, DeliveryController::class)->middleware('cashier');
Route::resource('product' 		 			, ProductController::class)->middleware('cashier');
Route::resource('client' 					, ClientController::class)->middleware('waiter');
Route::resource('user' 						, UserController::class)->middleware('admin');
Route::resource('discount'					, DiscountController::class)->middleware('cashier');

Route::resource('arching' 					, ArchingController::class)->middleware('cashier');
Route::get('arching/print/{id}'				, [ArchingController::class, 'print'])->middleware('cashier');
Route::get('arching/table/{id}'				, [ArchingController::class, 'show_table'])->middleware('cashier');

Route::resource('printer' 					, PrinterController::class)->middleware('cashier');
Route::get('printer/test/{ID}'				, [PrinterController::class, 'test'])->middleware('cashier');

Route::resource('retirement'				, RetirementController::class)->middleware('cashier');
Route::get('retirement/print/{ID}'			, [RetirementController::class, 'print'])->middleware('waiter');
Route::get('retirement/print/arching/{ID}'	, [RetirementController::class, 'print_arching'])->middleware('waiter');

Route::get('notification/query'				, [NotificationController::class, 'query'])->middleware('cashier');
Route::get('notification/all'				, [NotificationController::class, 'all'])->middleware('cashier');
Route::get('notification/read'				, [NotificationController::class, 'read'])->middleware('cashier');
Route::resource('notification'				, NotificationController::class)->middleware('cashier');

Route::post('search' 			 			, [FixedController::class, 'search'])->middleware('waiter');
Route::get('account'      					, [HomeController::class, 'account'])->middleware('waiter');
Route::post('contact'						, [HomeController::class, 'contact']);
Route::post('client/save'					, [ClientController::class, 'save'])->middleware('waiter');
Route::get('product/get/{id}'				, [ProductController::class, 'get'])->middleware('waiter');

Route::resource('fixed'						, FixedController::class)->middleware('admin');
Route::get('fixed/get/{id}'					, [FixedController::class, 'get'])->middleware('waiter');
Route::get('fixed/form/{id}/{type}'			, [FixedController::class, 'form'])->middleware('cashier');
Route::post('fixed/edit/name'				, [FixedController::class, 'edit_name'])->middleware('cashier');

Route::resource('table' 					, TableController::class)->middleware('waiter');
Route::get('table/history/{id}' 			, [TableController::class, 'history'])->middleware('waiter');
Route::get('table/close/{id}'      			, [TableController::class, 'close'])->middleware('cashier');
Route::get('table/charge/{id}'     			, [TableController::class, 'get_charge'])->middleware('cashier');
Route::post('table/charge/{id}'   			, [TableController::class, 'set_charge'])->middleware('cashier');
Route::get('table/print/{id}'      			, [TableController::class, 'print'])->middleware('cashier');
Route::post('table/discount/{id}'      		, [TableController::class, 'discount'])->middleware('cashier');

Route::resource('command' 					, CommandController::class)->middleware('waiter');
Route::get('command/print/{id}'    			, [CommandController::class, 'print'])->middleware('waiter');
Route::get('command/check/{id}' 			, [CommandController::class, 'check'])->middleware('waiter');
Route::post('command/delete/all' 			, [CommandController::class, 'delete_all'])->middleware('waiter');
Route::post('command/observation' 			, [CommandController::class, 'observation'])->middleware('waiter');

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    public function business()
    {
    	return $this->belongsTo('App\Models\Business');
    }

    public function products()
    {
    	return $this->hasMany('App\Models\Product');
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Supplier;
use Auth;

class SupplierController extends Controller
{
    private $path = "admin.supplier.";

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $suppliers = Auth::user()->business->suppliers->where('status', '!=', 'deleted');

        return view($this->path."index", compact('suppliers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->path."create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $supplier               = new Supplier();
        $supplier->name         = $request->name;
        $supplier->rut          = $request->rut;
        $supplier->address      = $request->address;
        $supplier->email        = $request->email;
        $supplier->phone        = $request->phone;
        $supplier->business_id  = Auth::user()->business->id;
        $supplier->save();

        return redirect('supplier');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $supplier = Supplier::find($id);

        if ($supplier->business == Auth::user()->business)
            return view($this->path."show", compact('supplier'));

        return redirect('home');
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $supplier = Supplier::find($id);

        if ($supplier->business == Auth::user()->business)
            return view($this->path."edit", compact('supplier'));

        return redirect('home');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $supplier = Supplier::find($id);

        if ($supplier->business == Auth::user()->business)
        {
            $supplier->name         = $request->name;
            $supplier->rut          = $request->rut;
            $supplier->address      = $request->address;
            $supplier->phone        = $request->phone;
            $supplier->save();

            return redirect('supplier');   
        }

        return redirect('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $supplier = Supplier::find($id);

        if ($supplier->business == Auth::user()->business)
        {
            $supplier->status = "deleted";
            $supplier->save();
            
            return redirect('supplier');
        }

        return redirect('home');
    }
}

resources/views/admin/supplier/create.blade.php
@extends('layouts.dashboard')

@section('title')
	@lang('message.suppliers')
@endsection

@section('content')

<div class="row">
	<div class="col-xs-12">
      	<div class="x_panel">
        	<div class="x_title">
          		<h2>@lang('message.suppliers_create')</h2>
          		<div class="clearfix"></div>
        	</div>
        	<div class="x_content">
          		<form action="{{url('supplier')}}" method="POST" class="form-horizontal col-xs-12 col-md-10 col-md-offset-1">
          			@csrf
          			<div class="form-group">
          				<label for="">@lang('message.name')</label>
          				<input type="text" name="name" class="form-control">
          			</div>
          			<div class="form-group">
          				<label for="">@lang('message.rut')</label>
          				<input type="text" name="rut" class="form-control">
          			</div>
          			<div class="form-group">
          				<label for="">@lang('message.address')</label>
          				<input type="text" name="address" class="form-control">
          			</div>
          			<div class="form-group">
          				<label for="">@lang('message.email')</label>
          				<input type="email" name="email" class="form-control">
          			</div>
          			<div class="form-group">
          				<label for="">@lang('message.phone')</label>
          				<input type="text" name="phone" class="form-control">
          			</div>
          			<div class="form-group">
          				<button class="btn btn-block btn-info">
          					<i class="fa fa-save"></i>
          					@lang('message.save')
          				</button>
          			</div>
          		</form>
          	</div>
          	<div class="x_footer">
          		<div class="col-xs-6">
          			<a href="{{URL::Previous()}}" class="btn btn-info">
          				<i class="fa fa-chevron-left"></i>
          				@lang('message.back')
          			</a>
          		</div>
          	</div>
        </div>
  	</div>
</div>
@endsection

resources/views/admin/supplier/edit.blade.php
@extends('layouts.dashboard')

@section('title')
	@lang('message.suppliers')
@endsection

@section('content')

<div class="row">
	<div class="col-xs-12">
      	<div class="x_panel">
        	<div class="x_title">
          		<h2>@lang('message.suppliers_edit')</h2>
          		<div class="clearfix"></div>
        	</div>
        	<div class="x_content">
          		<form action="{{url('supplier', $supplier->id)}}" method="POST" class="form-horizontal col-xs-12 col-md-10 col-md-offset-1">
          			@csrf
                <input type="hidden" name="_method" value="PATCH">
          			<div class="form-group">
          				<label for="">@lang('message.name')</label>
          				<input type="text" name="name" class="form-control" value="{{$supplier->name}}">
          			</div>
          			<div class="form-group">
          				<label for="">@lang('message.rut')</label>
          				<input type="text" name="rut" class="form-control" value="{{$supplier->rut}}">
          			</div>
          			<div class="form-group">
          				<label for="">@lang('message.address')</label>
          				<input type="text" name="address" class="form-control" value="{{$supplier->address}}">
          			</div>
          			<div class="form-group">
          				<label for="">@lang('message.email')</label>
          				<input type="email" name="email" class="form-control" value="{{$supplier->email}}">
          			</div>
          			<div class="form-group">
          				<label for="">@lang('message.phone')</label>
          				<input type="text" name="phone" class="form-control" value="{{$supplier->phone}}">
          			</div>
          			<div class="form-group">
          				<button class="btn btn-block btn-info">
          					<i class="fa fa-save"></i>
          					@lang('message.save')
          				</button>
          			</div>
          		</form>
          	</div>
          	<div class="x_footer">
          		<div class="col-xs-6">
          			<a href="{{URL::Previous()}}" class="btn btn-info">
          				<i class="fa fa-chevron-left"></i>
          				@lang('message.back')
          			</a>
          		</div>
          	</div>
        </div>
  	</div>
</div>
@endsection

resources/views/admin/supplier/index.blade.php
@extends('layouts.dashboard')

@section('title')
	@lang('message.suppliers')
@endsection

@section('content')

<div class="row">
	<div class="col-xs-12">
      	<div class="x_panel">
        	<div class="x_title">
        		<div class="row">
        			<div class="col-xs-6">
		          		<h2>@lang('message.suppliers')</h2>
		          		<div class="clearfix"></div>
        			</div>
        			<div class="col-xs-6">
        				<a href="{{url('admin')}}" class="btn btn-info">
	          				<i class="fa fa-chevron-left"></i>
	          				@lang('message.back')
	          			</a>
        			</div>
        		</div>
        	</div>
        	<div class="x_content">
          		<div class="table-responsive">
          			<table class="table table-striped">
          				<tr>
          					<th>@lang('message.name')</th>
          					<th>@lang('message.phone')</th>
          					<th>@lang('message.email')</th>
          					<th>@lang('message.view')</th>
          					<th>@lang('message.edit')</th>
          					<th>@lang('message.delete')</th>
          				</tr>
          				@foreach($suppliers as $supplier)
      							<tr>
      								<td>{{$supplier->name}}</td>
      								<td>{{$supplier->phone}}</td>
      								<td>{{$supplier->email}}</td>
      								<td>
      									<a href="{{url('supplier', $supplier->id)}}" class="btn btn-success">
      										<i class="fa fa-eye"></i>	
      									</a>
      								</td>
      								<td>
      									<a href="{{route('supplier.edit', $supplier->id)}}" class="btn btn-primary">
      										<i class="fa fa-edit"></i>
      									</a>
      								</td>
      								<td>
      									@include('helpers.delete', ['id' => $supplier->id, 'route' => 'supplier.destroy'])
      								</td>
      							</tr>
      						@endforeach
          			</table>
          		</div>
          	</div>
          	<div class="x_footer">
          		<div class="col-xs-6">
          			
          		</div>
          		<div class="col-xs-6 text-right">
					<a href="{{url('supplier/create')}}" class="btn btn-info">
						<i class="fa fa-plus"></i>
						@lang('message.create')
					</a>
          		</div>
          	</div>
        </div>
  	</div>
</div>
@endsection

resources/views/admin/supplier/show.blade.php
@extends('layouts.dashboard')

@section('title')
	@lang('message.suppliers')
@endsection

@section('content')

<div class="row">
	<div class="col-xs-12">
  	<div class="x_panel">
    	<div class="x_title">
        <div class="row">
          <div class="col-xs-6">
        		<h2>@lang('message.suppliers')</h2>
        		<div class="clearfix"></div>
          </div>
          <div class="col-xs-6">
            <a href="{{url('supplier')}}" class="btn btn-info">
              <i class="fa fa-chevron-left"></i>
              @lang('message.back')
            </a>
          </div>
        </div>
    	</div>
    	<div class="x_content">
    		<form class="form-horizontal col-xs-12 col-md-10 col-md-offset-1">
    			<div class="form-group">
    				<label for="">@lang('message.name')</label>
    				<input type="text" name="name" class="form-control" value="{{$supplier->name}}" readonly>
    			</div>
    			<div class="form-group">
    				<label for="">@lang('message.rut')</label>
    				<input type="text" name="rut" class="form-control" value="{{$supplier->rut}}" readonly>
    			</div>
    			<div class="form-group">
    				<label for="">@lang('message.address')</label>
    				<input type="text" name="address" class="form-control" value="{{$supplier->address}}" readonly>
    			</div>
    			<div class="form-group">
    				<label for="">@lang('message.email')</label>
    				<input type="email" name="email" class="form-control" value="{{$supplier->email}}" readonly>
    			</div>
    			<div class="form-group">
    				<label for="">@lang('message.phone')</label>
    				<input type="text" name="phone" class="form-control" value="{{$supplier->phone}}" readonly>
    			</div>
    		</form>
        <div class="col-xs-10 col-xs-offset-1">
          <br><br>
          <h2>@lang('message.products_of'): <b>{{$supplier->name}}</b></h2>
          <div class="clearfix"></div>
          <div class="table-responsive">
            <table class="table table-striped">
              <th>@lang('message.name')</th>
              <th>@lang('message.quantity')</th>
              <th>@lang('message.price')</th>
              <th>@lang('message.view')</th>
              <th>@lang('message.edit')</th>
              <th>@lang('message.delete')</th>
              
              @foreach($supplier->products->where('status', '!=', 'deleted') as $product)
                <tr>
                  <td>{{$product->name}}</td>
                  <td>{{$product->quantity}}</td>
                  <td>${{$product->price}}</td>
                  <td>
                    <a href="{{url('product', $product->id)}}" class="btn btn-success">
                      <i class="fa fa-eye"></i> 
                    </a>
                  </td>
                  <td>
                    <a href="{{route('product.edit', $product->id)}}" class="btn btn-primary">
                      <i class="fa fa-edit"></i>
                    </a>
                  </td>
                  <td>
                    @include('helpers.delete', ['id' => $product->id, 'route' => 'product.destroy'])
                  </td>
                </tr>
              @endforeach
            </table>
          </div>
      	</div>
      	<div class="x_footer">
      	</div>
      </div>
	   </div>
   </div>
</div>
@endsection