routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\BusinessController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ArchingController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommandController;
use App\Http\Controllers\PrinterController;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\TableController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\FixedController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\RetirementController;
use App\Http\Controllers\NotificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () 
{
    return view('welcome');
});

Route::get('show/tables/{id}' 		, function($id)
{
	$room = App\Models\Room::find($id);
    
    if($room != null)
    	return view('table.parts.show_tables', compact('room'));
});

Route::get('consult/tables' 		, function()
{
	return Auth::user()->business->fixeds->where('status','occupied')->count();
});

Route::get('show/tabs/{id}'			, function($id)
{
	$room = App\Models\Room::find($id);
    return view('table.parts.tabs', compact('room'));
});

Route::get('show/commands/{id}'			, function($id)
{
	$fixed 		= App\Models\Fixed::find($id);
	$table      = $fixed->tables->where('status', 'enabled')->first();
    
    return view('table.parts.command_list', compact('table'));
});

Auth::routes();

Route::get('business/check/{id}'			, [BusinessController::class, 'check']);

Route::get('/home'							, [HomeController::class, 'index'])->middleware('waiter');
Route::get('/admin'							, [HomeController::class, 'admin'])->middleware('waiter');

Route::resource('business' 					, BusinessController::class)->middleware('admin');
Route::resource('category'	 				, CategoryController::class)->middleware('cashier');
Route::resource('reservation' 				, ReservationController::class)->middleware('waiter');
Route::resource('setting' 					, SettingController::class)->middleware('cashier');
Route::resource('supplier' 					, SupplierController::class)->middleware('cashier');
Route::resource('ticket' 					, TicketController::class)->middleware('waiter');
Route::resource('room' 						, RoomController::class)->middleware('waiter');
Route::resource('delivery'					, DeliveryController::class)->middleware('cashier');
Route::resource('product' 		 			, ProductController::class)->middleware('cashier');
Route::resource('client' 					, ClientController::class)->middleware('waiter');
Route::resource('user' 						, UserController::class)->middleware('admin');
Route::resource('discount'					, DiscountController::class)->middleware('cashier');

Route::resource('arching' 					, ArchingController::class)->middleware('cashier');
Route::get('arching/print/{id}'				, [ArchingController::class, 'print'])->middleware('cashier');
Route::get('arching/table/{id}'				, [ArchingController::class, 'show_table'])->middleware('cashier');

Route::resource('printer' 					, PrinterController::class)->middleware('cashier');
Route::get('printer/test/{ID}'				, [PrinterController::class, 'test'])->middleware('cashier');

Route::resource('retirement'				, RetirementController::class)->middleware('cashier');
Route::get('retirement/print/{ID}'			, [RetirementController::class, 'print'])->middleware('waiter');
Route::get('retirement/print/arching/{ID}'	, [RetirementController::class, 'print_arching'])->middleware('waiter');

Route::get('notification/query'				, [NotificationController::class, 'query'])->middleware('cashier');
Route::get('notification/all'				, [NotificationController::class, 'all'])->middleware('cashier');
Route::get('notification/read'				, [NotificationController::class, 'read'])->middleware('cashier');
Route::resource('notification'				, NotificationController::class)->middleware('cashier');

Route::post('search' 			 			, [FixedController::class, 'search'])->middleware('waiter');
Route::get('account'      					, [HomeController::class, 'account'])->middleware('waiter');
Route::post('contact'						, [HomeController::class, 'contact']);
Route::post('client/save'					, [ClientController::class, 'save'])->middleware('waiter');
Route::get('product/get/{id}'				, [ProductController::class, 'get'])->middleware('waiter');

Route::resource('fixed'						, FixedController::class)->middleware('admin');
Route::get('fixed/get/{id}'					, [FixedController::class, 'get'])->middleware('waiter');
Route::get('fixed/form/{id}/{type}'			, [FixedController::class, 'form'])->middleware('cashier');
Route::post('fixed/edit/name'				, [FixedController::class, 'edit_name'])->middleware('cashier');

Route::resource('table' 					, TableController::class)->middleware('waiter');
Route::get('table/history/{id}' 			, [TableController::class, 'history'])->middleware('waiter');
Route::get('table/close/{id}'      			, [TableController::class, 'close'])->middleware('cashier');
Route::get('table/charge/{id}'     			, [TableController::class, 'get_charge'])->middleware('cashier');
Route::post('table/charge/{id}'   			, [TableController::class, 'set_charge'])->middleware('cashier');
Route::get('table/print/{id}'      			, [TableController::class, 'print'])->middleware('cashier');
Route::post('table/discount/{id}'      		, [TableController::class, 'discount'])->middleware('cashier');

Route::resource('command' 					, CommandController::class)->middleware('waiter');
Route::get('command/print/{id}'    			, [CommandController::class, 'print'])->middleware('waiter');
Route::get('command/check/{id}' 			, [CommandController::class, 'check'])->middleware('waiter');
Route::post('command/delete/all' 			, [CommandController::class, 'delete_all'])->middleware('waiter');
Route::post('command/observation' 			, [CommandController::class, 'observation'])->middleware('waiter');

app/Models/Printer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Printer extends Model
{
    public function business()
    {
    	return $this->belongsTo('App\Models\Business');
    }

    public function products()
    {
    	return $this->hasMany('App\Models\Product');
    }

    public function tickets()
    {
    	return $this->hasMany('App\Models\Ticket');
    }

    public function commands()
    {
        return $this->hasMany('App\Models\Command');
    }
}

app/Http/Controllers/PrinterController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Printer;
use App\Models\Ticket;
use Auth;

class PrinterController extends Controller
{
    private $path = "admin.printer.";

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $printers = Auth::user()->business->printers->where('status', 'enabled');
        
        return view($this->path."index", compact("printers"));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->path."create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $printer                = new Printer();
        $printer->name          = $request->name;
        $printer->code          = $request->code;
        $printer->business_id   = Auth::user()->business->id;
        $printer->save();

        return redirect("printer");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $printer = Printer::find($id);

        if ($printer->business == Auth::user()->business) 
        {
            return view($this->path."show", compact('printer'));
        }

        return redirect('home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $printer = Printer::find($id);

        if ($printer->business == Auth::user()->business) 
        {
            return view($this->path."edit", compact('printer'));
        }

        return redirect('home');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $printer = Printer::find($id);

        if ($printer->business_id == Auth::user()->business_id) 
        {
            $printer->name      = $request->name;
            $printer->address   = $request->address;
            $printer->save();

            return redirect("printer");
        }

        return redirect('home');
    }

    public function test($id)
    {
        $printer = Printer::find($id);

        $content = "<div class='row'>
                        <div class='col text-center'>
                            <h1>
                                RestoAPP.uy
                            </h1>
                        </div>
                        <hr>
                        <div class='col text-center'>
                            <h2>Prueba de la impresora \"".$printer->name."\"</h2>
                        </div>
                    </div>";

        if(print_ticket($id, 'test', $content))
            Session(['success' => 'Se envio una prueba a la impresora: '.$printer->name]);
        else
            Session(['error' => 'No se pudo enviar a imprimir']);
        
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $printer = Printer::find($id);

        if ($printer->business == Auth::user()->business) 
        {
            foreach($printer->products->where('status', '!=', 'deleted') as $product)
            {
                $product->printer_id = null;
                $product->save();
            }
            
            $printer->status = "deleted";
            $printer->save();
            
            return redirect("printer");
        }

        return redirect('home');
    }
}

resources/views/admin/printer/create.blade.php
@extends('layouts.dashboard')

@section('title')
	@lang('message.printers')
@endsection

@section('content')

<div class="row">
	<div class="col-xs-12">
      	<div class="x_panel">
        	<div class="x_title">
          		<div class="row">
                <div class="col-xs-6">
                  <h2>@lang('message.printers_create')</h2>
                  <div class="clearfix"></div>
                </div>
                <div class="col-xs-6 text-right">
                  <a href="{{URL::Previous()}}" class="btn btn-default">
                    <i class="fa fa-chevron-left"></i>
                    @lang('message.back')
                  </a>  
                </div>
              </div>
        	</div>
        	<div class="x_content">
          		<form action="{{url('printer')}}" method="POST" class="form-horizontal col-xs-12 col-md-6 col-md-offset-3">
          			@csrf
          			<div class="form-group">
          				<label for="">@lang('message.name')</label>
          				<input type="text" name="name" class="form-control">
          			</div>

                @php
                  $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
                  
                  $charactersLength = strlen($characters);
                  
                  $randomString = '';

                  for ($i = 0; $i < 10; $i++)
                      $randomString .= $characters[rand(0, $charactersLength - 1)];
                @endphp

          			<div class="form-group">
          				<label for="">@lang('message.code')</label>
          				<input type="text" name="code" class="form-control" value="{{$randomString}}" readonly>
          			</div>
          			<div class="form-group text-right">
          				<button class="btn btn-info">
          					<i class="fa fa-save"></i>
          					@lang('message.save')
          				</button>
          			</div>
          		</form>
          	</div>
          	<div class="x_footer">
          		<div class="col-xs-6">
          			
          		</div>
          	</div>
        </div>
  	</div>
</div>
@endsection

resources/views/admin/printer/edit.blade.php
@extends('layouts.dashboard')

@section('title')
  @lang('message.printers')
@endsection

@section('content')

<div class="row">
  <div class="col-xs-12">
        <div class="x_panel">
          <div class="x_title">
              <div class="row">
                <div class="col-xs-6">
                  <h2>@lang('message.printers_edit')</h2>
                  <div class="clearfix"></div>
                </div>
                <div class="col-xs-6 text-right">
                  <a href="{{URL::Previous()}}" class="btn btn-default">
                    <i class="fa fa-chevron-left"></i>
                    @lang('message.back')
                  </a>  
                </div>
              </div>
          </div>
          <div class="x_content">
              <form action="{{url('printer', $printer->id)}}" method="POST" class="form-horizontal col-xs-12 col-md-6 col-md-offset-3">
                @csrf
                <input type="hidden" name="_method" value="PATCH">
                <div class="form-group">
                  <label for="">@lang('message.name')</label>
                  <input type="text" name="name" class="form-control" value="{{$printer->name}}">
                </div>

                <div class="form-group">
                  <label for="">@lang('message.code')</label>
                  <input type="text" name="code" class="form-control" value="{{$printer->code}}" readonly>
                </div>
                <div class="form-group text-right">
                  <button class="btn btn-info">
                    <i class="fa fa-save"></i>
                    @lang('message.save')
                  </button>
                </div>
              </form>
            </div>
            <div class="x_footer">
              <div class="col-xs-6">
                
              </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/printer/index.blade.php
@extends('layouts.dashboard')

@section('title')
	@lang('message.printers')
@endsection

@section('content')

<div class="row">
	<div class="col-xs-12">
      	<div class="x_panel">
        	<div class="x_title">
        		<div class="row">
        			<div class="col-xs-6">
		          		<h3>@lang('message.printers')</h3>
		          		<div class="clearfix"></div>
        			</div>
        			<div class="col-xs-6 text-right">
        				<a href="{{url('admin')}}" class="btn btn-default">
	          				<i class="fa fa-chevron-left"></i>
	          				@lang('message.back')
	          			</a>
        			</div>
        		</div>
        	</div>
        	<div class="x_content">
          		<div class="table-responsive">
          			<table class="table table-striped">
          				<th>@lang('message.name')</th>
          				<th>@lang('message.code')</th>
          				<th>@lang('message.status')</th>
          				<th>@lang('message.view')</th>
          				<th>@lang('message.edit')</th>
          				<th>@lang('message.test')</th>
          				<th>@lang('message.delete')</th>
          				
          				@foreach($printers as $printer)
							<tr>
								<td>{{$printer->name}}</td>
								<td>{{$printer->code}}</td>
								<td>
									@if(check_printer($printer->id))
										<p style="padding:10px; width:110px; border-radius: 5px; color:white; background: #28bd28; text-align: center; ">Online</p>
									@else
										<p style="padding:10px; width:110px; border-radius: 5px; color:white; background: #e02c2c; text-align: center; ">Fuera de linea</p>
									@endif
								</td>
								<td>
									<a href="{{url('printer', $printer->id)}}" class="btn btn-success">
										<i class="fa fa-eye"></i>
									</a>
								</td>
								<td>
									<a href="{{route('printer.edit', $printer->id)}}" class="btn btn-primary">
										<i class="fa fa-edit"></i>
									</a>
								</td>
								<td>
									@if(\Carbon\Carbon::now()->diffInSeconds($printer->updated_at) < 10)
										<a href="{{url('printer/test', $printer->id)}}" class="btn btn-warning">
											<i class="fa fa-print"></i>
										</a>
									@else
										<a class="btn btn-warning disabled" disabled>
											<i class="fa fa-print"></i>
										</a>
									@endif
								</td>
								<td>
									@include('helpers.delete', ['id' => $printer->id, 'route' => 'printer.destroy'])
								</td>
							</tr>
						@endforeach
          			</table>
          		</div>
          	</div>
          	<div class="x_footer">
          		<div class="col-xs-6">
          			
          		</div>
          		<div class="col-xs-6 text-right">
					<a href="{{url('printer/create')}}" class="btn btn-info">
						<i class="fa fa-plus"></i>
						@lang('message.create')
					</a>
          		</div>
          	</div>
        </div>
  	</div>
</div>
@endsection

resources/views/admin/printer/show.blade.php
@extends('layouts.dashboard')

@section('title')
	@lang('message.categories')
@endsection

@section('content')

<div class="row">
	<div class="col-xs-12">
      	<div class="x_panel">
        	<div class="x_title">
        		<div class="row">
        			<div class="col-xs-6">
        				<h3>@lang('message.products_of'): <b>{{$printer->name}}</b></h3>
          				<div class="clearfix"></div>	
        			</div>
        			<div class="col-xs-6 text-right">
        				<a href="{{url('printer')}}" class="btn btn-default">
	          				<i class="fa fa-chevron-left"></i>
	          				@lang('message.back')
	          			</a>
        			</div>
        		</div>
        	</div>
        	<div class="x_content">
          		<div class="table-responsive">
          			<table class="table table-striped">
          				<th>@lang('message.name')</th>
          				<th>@lang('message.quantity')</th>
          				<th>@lang('message.price')</th>
          				<th>@lang('message.view')</th>
          				<th>@lang('message.edit')</th>
          				<th>@lang('message.delete')</th>
          				
          				@foreach($printer->products->where('status', '!=', 'deleted') as $product)
							<tr>
								<td>{{$product->name}}</td>
								<td>{{$product->quantity}}</td>
								<td>${{$product->price}}</td>
								<td>
									<a href="{{url('product', $product->id)}}" class="btn btn-success">
										<i class="fa fa-eye"></i>	
									</a>
								</td>
								<td>
									<a href="{{route('product.edit', $product->id)}}" class="btn btn-primary">
										<i class="fa fa-edit"></i>
									</a>
								</td>
								<td>
									<!-- Button trigger modal -->
									<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
										<i class="fa fa-trash"></i>
									</button>

									<!-- Modal -->
									<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
										<div class="modal-dialog" role="document">
											<div class="modal-content">
												<div class="modal-header">
													<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
													
												</div>
												<div class="modal-body text-center">
													<h3>@lang('message.delete_question')</h3>
												</div>
												<div class="modal-footer">
													<div class="col-xs-6">
														<button type="button" class="btn btn-default btn-block" data-dismiss="modal">@lang('message.no')</button>
													</div>
													<div class="col-xs-6">
														<form action="{{ route('product.destroy', $product->id) }}" method="POST">
					                                        {{ csrf_field() }}
					                                        <input type="hidden" name="_method" value="DELETE">
					                                        <button type="submit" class="btn btn-danger btn-block">   
					                                            @lang('message.yes')
					                                        </button>
					                                    </form>
													</div>
												</div>
											</div>
										</div>
									</div>
								</td>
							</tr>
						@endforeach
          			</table>
          		</div>
          	</div>
          	<div class="x_footer">
          		<div class="col-xs-6">
          			
          		</div>
          		<div class="col-xs-6 text-right">
					
          		</div>
          	</div>
        </div>
  	</div>
</div>
@endsection