routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\BusinessController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ArchingController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommandController;
use App\Http\Controllers\PrinterController;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\TableController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\FixedController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\RetirementController;
use App\Http\Controllers\NotificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () 
{
    return view('welcome');
});

Route::get('show/tables/{id}' 		, function($id)
{
	$room = App\Models\Room::find($id);
    
    if($room != null)
    	return view('table.parts.show_tables', compact('room'));
});

Route::get('consult/tables' 		, function()
{
	return Auth::user()->business->fixeds->where('status','occupied')->count();
});

Route::get('show/tabs/{id}'			, function($id)
{
	$room = App\Models\Room::find($id);
    return view('table.parts.tabs', compact('room'));
});

Route::get('show/commands/{id}'			, function($id)
{
	$fixed 		= App\Models\Fixed::find($id);
	$table      = $fixed->tables->where('status', 'enabled')->first();
    
    return view('table.parts.command_list', compact('table'));
});

Auth::routes();

Route::get('business/check/{id}'			, [BusinessController::class, 'check']);

Route::get('/home'							, [HomeController::class, 'index'])->middleware('waiter');
Route::get('/admin'							, [HomeController::class, 'admin'])->middleware('waiter');

Route::resource('business' 					, BusinessController::class)->middleware('admin');
Route::resource('category'	 				, CategoryController::class)->middleware('cashier');
Route::resource('reservation' 				, ReservationController::class)->middleware('waiter');
Route::resource('setting' 					, SettingController::class)->middleware('cashier');
Route::resource('supplier' 					, SupplierController::class)->middleware('cashier');
Route::resource('ticket' 					, TicketController::class)->middleware('waiter');
Route::resource('room' 						, RoomController::class)->middleware('waiter');
Route::resource('delivery'					, DeliveryController::class)->middleware('cashier');
Route::resource('product' 		 			, ProductController::class)->middleware('cashier');
Route::resource('client' 					, ClientController::class)->middleware('waiter');
Route::resource('user' 						, UserController::class)->middleware('admin');
Route::resource('discount'					, DiscountController::class)->middleware('cashier');

Route::resource('arching' 					, ArchingController::class)->middleware('cashier');
Route::get('arching/print/{id}'				, [ArchingController::class, 'print'])->middleware('cashier');
Route::get('arching/table/{id}'				, [ArchingController::class, 'show_table'])->middleware('cashier');

Route::resource('printer' 					, PrinterController::class)->middleware('cashier');
Route::get('printer/test/{ID}'				, [PrinterController::class, 'test'])->middleware('cashier');

Route::resource('retirement'				, RetirementController::class)->middleware('cashier');
Route::get('retirement/print/{ID}'			, [RetirementController::class, 'print'])->middleware('waiter');
Route::get('retirement/print/arching/{ID}'	, [RetirementController::class, 'print_arching'])->middleware('waiter');

Route::get('notification/query'				, [NotificationController::class, 'query'])->middleware('cashier');
Route::get('notification/all'				, [NotificationController::class, 'all'])->middleware('cashier');
Route::get('notification/read'				, [NotificationController::class, 'read'])->middleware('cashier');
Route::resource('notification'				, NotificationController::class)->middleware('cashier');

Route::post('search' 			 			, [FixedController::class, 'search'])->middleware('waiter');
Route::get('account'      					, [HomeController::class, 'account'])->middleware('waiter');
Route::post('contact'						, [HomeController::class, 'contact']);
Route::post('client/save'					, [ClientController::class, 'save'])->middleware('waiter');
Route::get('product/get/{id}'				, [ProductController::class, 'get'])->middleware('waiter');

Route::resource('fixed'						, FixedController::class)->middleware('admin');
Route::get('fixed/get/{id}'					, [FixedController::class, 'get'])->middleware('waiter');
Route::get('fixed/form/{id}/{type}'			, [FixedController::class, 'form'])->middleware('cashier');
Route::post('fixed/edit/name'				, [FixedController::class, 'edit_name'])->middleware('cashier');

Route::resource('table' 					, TableController::class)->middleware('waiter');
Route::get('table/history/{id}' 			, [TableController::class, 'history'])->middleware('waiter');
Route::get('table/close/{id}'      			, [TableController::class, 'close'])->middleware('cashier');
Route::get('table/charge/{id}'     			, [TableController::class, 'get_charge'])->middleware('cashier');
Route::post('table/charge/{id}'   			, [TableController::class, 'set_charge'])->middleware('cashier');
Route::get('table/print/{id}'      			, [TableController::class, 'print'])->middleware('cashier');
Route::post('table/discount/{id}'      		, [TableController::class, 'discount'])->middleware('cashier');

Route::resource('command' 					, CommandController::class)->middleware('waiter');
Route::get('command/print/{id}'    			, [CommandController::class, 'print'])->middleware('waiter');
Route::get('command/check/{id}' 			, [CommandController::class, 'check'])->middleware('waiter');
Route::post('command/delete/all' 			, [CommandController::class, 'delete_all'])->middleware('waiter');
Route::post('command/observation' 			, [CommandController::class, 'observation'])->middleware('waiter');

app/Http/Controllers/TableController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Table;
use App\Models\Fixed;
use App\Models\Room;
use App\Models\Ticket;
use App\Models\Discount;
use App\Models\Arching;
use Auth;

class TableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $fixed                  = Fixed::find($request->table);
        $fixed->status          = "occupied";
        $fixed->save();

        $table                  = new Table();
        $table->diners          = $request->diners;
        $table->observation     = $request->observation;
        $table->user_id         = $request->waiter;
        $table->client_id       = $request->client;
        $table->fixed_id        = $request->table;  
        $table->arching_id      = Arching::where('status', 'enabled')->first()->id;
        $table->status          = "enabled";
        $table->save();

        return redirect('table/'.$fixed->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $fixed = Fixed::find($id);

        if ($fixed->business == Auth::user()->business)
        {
            $table      = $fixed->tables->where('status', 'enabled')->first();
            
            if ($table != null)
                return view('table.show', compact('table', 'fixed'));
            else
                return redirect('home');
        }
        
        return redirect('home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $table = Table::find($id);

        $table->fixed->status = "enabled";
        $table->fixed->save();

        $table->delete();

        return redirect('room/'.$table->fixed->room->id);        
    }

    public function close($id)
    {
        $table = Table::find($id);
        
        if ($table->fixed->business->id == Auth::user()->business->id) 
        {

            $table->fixed->status = "enabled";
            $table->fixed->save();

            $table->status  = "disabled";
            $table->total   = ($table->commands->sum('pay') - $table->discounts->sum('quantity'));
            $table->save();

            return redirect('room/'.$table->fixed->room->id);
        }
        
        return redirect('home');

    }

    public function get_charge($id)
    {
        $table = Table::find($id);
        
        if ($table->fixed->business->id == Auth::user()->business->id) 
        {
            
            $commands_list  = $table->commands->where('status', '!=', 'pending')->where('status', '!=', 'deleted')->groupBy('product_id');
            $commands_all   = $table->commands->where('status', '!=', 'pending')->where('status', '!=', 'deleted');


            return view('table.charge', compact('table', 'commands_list', 'commands_all'));
        }

        return back();   
    }

    public function set_charge(Request $request, $id)
    {   
        $table = Table::find($id);

        $flag  = false;
        $total = 0;
        
        //controlo si hay alguna comanda seleccionada para pagar por separado
        foreach ($table->commands->where('status', '!=', 'deleted') as $command) 
        {
            if ($request['check_'.$command->id] == "yes") 
            {
                $flag   = true;
                $total  += $command->price;
                
                $command->status        = "disabled";
                $command->wayOfPay      = $request->wayOfPay;
                $command->pay           = $command->price;

                $command->save();
            }
        }

        //si $flag esta en false es que no entro en el if anterior, es decir que no hay ninguna comanda seleccionada y por eso las selecciono todas
        if ($flag == false) 
        {
            foreach ($table->commands->where('status', '!=', 'deleted') as $command) 
            {
                if($command->status == "enabled")
                {
                    $total += $command->price;
                    
                    $command->status        = "disabled";
                    $command->wayOfPay      = $request->wayOfPay;
                    $command->pay           = $command->price;

                    $command->save();
                }
            }
        }
            
        return back()->with('total', $total);
    }

    public function history($id)
    {
        $table = Table::find($id);

        if($table->fixed->business == Auth::user()->business)
        {
            $commands_list  = $table->commands->where('status', 'enabled')->groupBy('product_id');
            
            return view("table.history", compact('commands_list', 'table'));
        }

        return back();   
    }

    public function print($id)
    {
        $table          = Table::find($id);
        $total          = 0;
        $total_discount = 0;

        if($table->commands->where('status', 'enabled')->count() == 0)
        {
            Session(["error" => "No hay nada para imprimir en esta mesa"]);
            return back();   
        }

        $content    = "
            <div class='row'>
                <div class='col text-center'>
                    <h3>
                        Cuenta de Mesa ".$table->fixed->name."
                    </h3>
                    <p>
                        ".\Carbon\Carbon::now('America/Montevideo')->format('d/m/Y h:i')."
                    </p>
                </div>
            </div>
        ";

        foreach($table->commands->where('status', 'enabled')->groupBy('product_id') as $commands)
        {
            $content .= 
                "<div class='row'>
                    <div class='text-left' style='float:left;width: 60%;'>
                        <b>".$commands->first()->product_name."</b>
                    </div>
                    <div class='text-center' style='float:left;width: 40%;'>
                        <b>x".$commands->count()." $".$commands->count() * $commands->first()->price."</b>
                    </div>
                </div><hr>";
            
            $total += $commands->count() * $commands->first()->price;
            $flag = true;
        }

        foreach($table->discounts->where('status', '!=', 'deleted') as $discount)
        {
            if($discount->type == "quantity") 
                $total_discount += $discount->quantity;
            else 
                $total_discount += ($table->commands->where('status', 'enabled')->sum('price') * $discount->quantity) / 100;
        }

        if($total_discount != 0)
        {
            $content .= 
            "<div class='row'>
                <div class='col-left text-left'>
                    <b>Sub total:</b>
                </div>
                <div class='col-right text-center'>
                    <b>$ ".$total."</b>
                </div>
            </div>
            <div class='row'>
                <div class='col-left text-left'>
                    <b>Descuento:</b>
                </div>
                <div class='col-right text-center'>
                    <b>$ ".$total_discount."</b>
                </div>
            </div><hr>";
        }

        $content .= 
            "<div class='row'>
                <div class='col-left text-left'>
                    <b>Total:</b>
                </div>
                <div class='col-right text-center'>
                    <b>$ ".($total - $total_discount)."</b>
                </div>
                <br>
                <div class='col-xs-12 text-center'>
                    <p>-- Fin de cuenta --</p>
                </div>
            </div>";
        

        if(Auth::user()->business->printer_admin == null)
        {
            Session(["error" => "No hay una impresora predeterminada para imprimir los tickets de caja, debe seleccionarla desde la sección de opciones."]);
            
            return back();
        }
        
        if(print_ticket(Auth::user()->business->printer_admin, 'table', $content))
            Session(['success' => 'Se envio a imprimir el ticket']);
        else
            Session(['error' => 'No se pudo imprimir el retiro.']);

        return back();   
    }
}

resources/views/table/account.blade.php
@extends('layouts.tables')

@section('content')
<div class="container-fluid table-container">
    @include('helpers.alert')
    <div class="row body">
		<div class="col-xs-12 details_title text-center bg-primary">
        	<div class="col-xs-6 col-xs-offset-3">
                <p>Mi cuenta</p>     
            </div>
            <div class="col-xs-3 text-right">
                <a href="{{url('home')}}" class="btn btn-default">
                    <i class="fa fa-chevron-left"></i>
                    Volver
                </a>
            </div>
        </div>
        <div class="col-xs-12">
            
        </div>
    </div>
</div>
@endsection

@section('scripts')
   
@endsection

resources/views/table/client.blade.php
@extends('layouts.tables')

@section('content')
<div class="container table-container">
    @include('helpers.alert')
    <div class="row body">
		<div class="col-xs-12 details_title text-center bg-primary">
        	<div class="col-xs-6 col-xs-offset-3">
                <p>@lang('message.client'): {{$client->name}}</p>     
            </div>
            <div class="col-xs-3 text-right">
                <a href="{{URL::Previous()}}" class="btn btn-default">
                    <i class="fa fa-chevron-left"></i>
                    Volver
                </a>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="col-xs-12">
                <h3>Pedidos Favoritos</h3>
                <hr>
                <div class="table table-responsive">
                    <table class="table table-striped">
                        <tr>
                            <th>Nombre</th>
                            <th>Cantidad</th>
                        </tr>
                        @php
                            $commands = $client->commands->where('status', 'enabled')->groupBy('product_id');
                        @endphp
                        
                        @foreach($commands as $command)
                            <tr>
                                <td>
                                    {{$command->first()->product->name}}
                                </td>
                                <td>
                                    {{$command->count()}}
                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
            <div class="col-xs-12">
                <h3>Ultimas visitas</h3>
                <hr>
                <div class="table table-responsive">
                    <table class="table table-striped">
                        <tr>
                            <th>Mesa</th>
                            <th>Gasto</th>
                            <th>Fecha</th>
                        </tr>
                        @foreach($client->tables->take(5) as $table)
                            <tr>
                                <td>
                                    Mesa: {{$table->fixed->name}}
                                </td>
                                <td>
                                    {{$table->created_at->format('d/m/Y H:i')}}
                                </td>
                                <td>
                                    ${{($table->commands->sum('price') - $table->discounts->sum('quantity'))}}
                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
   
@endsection

resources/views/table/history.blade.php
@extends('layouts.tables')

@section('content')
<div class="container-fluid table-container">
    <div class="row body">
		<div class="col-xs-12 details_title text-center bg-primary">
            <div class="col-xs-6 col-xs-offset-3">
                <p>@lang('message.commands_table'): {{$table->fixed->name}}</p>
            </div>
            <div class="col-xs-3 text-right">
                <a href="{{URL::Previous()}}" class="btn btn-default">
                    <i class="fa fa-chevron-left"></i>
                    Volver
                </a>
            </div>
        </div>
        <div class="col-xs-12 col-md-10 col-md-offset-1 text-center">
        	<div class="table table-responsive">
        		<br>
        		<table class="table table_border table-striped text-center" >
            			<tr>
            				<th class="text-center">@lang('message.product')</th>
                            <th class="text-center">@lang('message.quantity')</th>
            				<th class="text-center">@lang('message.price')</th>
            				<th class="text-center"></th>
            			</tr>
            			@foreach($commands_list as $commands)
							<tr>
								<td>{{$commands->first()->product->name}}</td>
                                <td>x {{$commands->count()}}</td>
								<td>$ {{$commands->first()->price * $commands->count()}}</td>
								<td>
                                    @if((Auth::user()->type == "admin") or (Auth::user()->type == "cashier"))
                                        @if($commands->count() > 1)                      
                                            <!-- Button trigger modal -->
                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#commands_delete_all_{{$commands->first()->id}}">
                                                <i class="fa fa-times"></i>
                                            </button>
                        
                                            <!-- Modal -->
                                            <div class="modal fade" id="commands_delete_all_{{$commands->first()->id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                        </div>
                                                        <form action="{{url('command/delete/all')}}" method="POST">
                                                            {{ csrf_field() }}
                                                            <input type="hidden" name="table" value="{{$table->id}}">
                                                            <input type="hidden" name="product" value="{{$commands->first()->product->id}}">
                                                            <input type="hidden" name="status" value="enabled">
                                                            
                                                            <div class="modal-body text-center">
                                                                <h3>@lang('message.delete_question_number')</h3>
                                                                <div class="row">
                                                                    <div class="col-xs-12 col-md-4 col-md-offset-4">
                                                                        <input type="number" name="quantity" value="1" class="form-control" min=1 max={{$commands->count()}}>
                                                                        <br>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <div class="col-xs-6">
                                                                    <button type="button" class="btn btn-default btn-block" data-dismiss="modal">@lang('message.no')</button>
                                                                </div>
                                                                <div class="col-xs-6">
                                                                    <button type="submit" class="btn btn-danger btn-block">   
                                                                        @lang('message.yes')
                                                                    </button>     
                                                                </div>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>       
                                        @else
                                            <!-- Button trigger modal -->
                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#commands_delete_{{$commands->first()->id}}">
                                                <i class="fa fa-times"></i>
                                            </button>
                        
                                            <!-- Modal -->
                                            <div class="modal fade" id="commands_delete_{{$commands->first()->id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                        </div>
                                                        <div class="modal-body text-center">
                                                            <h3>@lang('message.delete_question')</h3>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <div class="col-xs-6">
                                                                <button type="button" class="btn btn-default btn-block" data-dismiss="modal">@lang('message.no')</button>
                                                            </div>
                                                            <div class="col-xs-6">
                                                                <form action="{{ route('command.destroy', $commands->first()->id) }}" method="POST">
                                                                    {{ csrf_field() }}
                                                                    <input type="hidden" name="_method" value="DELETE">
                                                                    
                                                                    <button type="submit" class="btn btn-danger btn-block">   
                                                                        @lang('message.yes')
                                                                    </button>
                                                                </form>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>                       
                                        @endif
                                    @endif
                                </td>
							</tr>
            			@endforeach
                        <tfoot>
                            <td></td>
                            <td></td>
                            <td><b>@lang('message.total'):</b> <b>$</b><b id="total">{{$table->commands->where('status', 'enabled')->sum('price')}}</b></td>
                            <td></td>
                        </tfoot>
            		</table>
        	</div>
        </div>
    </div>
</div>
@endsection

resources/views/table/home.blade.php
@extends('layouts.tables')

@section('content')
    <div class="container-fluid table-container mt-3">
        <div class="row">
            
            @include('table.parts.clock')
            
            <div class="col-12 col-md-9">
                
                {{-- Navegacion de las mesas--}}
                <ul class="nav nav-tabs" id="show_tabs">
                    @include('table.parts.tabs')

                    @if(Auth::user()->type == "admin")
                        {{--Boton de editar sala--}}
                        <li>
                            <a href="{{route('room.edit', $room->id)}}" class="nav-link">
                                <i class="fa fa-edit"></i>
                            </a>
                        </li>
                    @endif
                </ul>
                {{-- Fin navegacion de las mesas--}}

                
            </div>  
        </div>
        <div class="row body">
            <div class="col-xs-12 tables hidden-xs">
                <div id="show_tables">
                    @include('table.parts.show_tables')
                </div>
            </div>

            <div class="col-xs-12 tables visible-xs">
                <div id="show_tables">
                    @include('table.parts.show_tables_mobile')
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function()
        {
             reload();

            function reload()
            {
                $.get("{{url('consult/tables')}}", function(res)
                {
                    if ("{{Auth::user()->business->fixeds->where('status','occupied')->count()}}" != res )
                    {       
                        $('#show_tables').load("{{url('show/tables', $room->id)}}");
                        $('#show_tabs').load("{{url('show/tabs', $room->id)}}");
                    }

                });

                setTimeout(reload, 5000);
            }
        });
    </script>
@endsection