routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\BusinessController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ArchingController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommandController;
use App\Http\Controllers\PrinterController;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\TableController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\FixedController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\RetirementController;
use App\Http\Controllers\NotificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () 
{
    return view('welcome');
});

Route::get('show/tables/{id}' 		, function($id)
{
	$room = App\Models\Room::find($id);
    
    if($room != null)
    	return view('table.parts.show_tables', compact('room'));
});

Route::get('consult/tables' 		, function()
{
	return Auth::user()->business->fixeds->where('status','occupied')->count();
});

Route::get('show/tabs/{id}'			, function($id)
{
	$room = App\Models\Room::find($id);
    return view('table.parts.tabs', compact('room'));
});

Route::get('show/commands/{id}'			, function($id)
{
	$fixed 		= App\Models\Fixed::find($id);
	$table      = $fixed->tables->where('status', 'enabled')->first();
    
    return view('table.parts.command_list', compact('table'));
});

Auth::routes();

Route::get('business/check/{id}'			, [BusinessController::class, 'check']);

Route::get('/home'							, [HomeController::class, 'index'])->middleware('waiter');
Route::get('/admin'							, [HomeController::class, 'admin'])->middleware('waiter');

Route::resource('business' 					, BusinessController::class)->middleware('admin');
Route::resource('category'	 				, CategoryController::class)->middleware('cashier');
Route::resource('reservation' 				, ReservationController::class)->middleware('waiter');
Route::resource('setting' 					, SettingController::class)->middleware('cashier');
Route::resource('supplier' 					, SupplierController::class)->middleware('cashier');
Route::resource('ticket' 					, TicketController::class)->middleware('waiter');
Route::resource('room' 						, RoomController::class)->middleware('waiter');
Route::resource('delivery'					, DeliveryController::class)->middleware('cashier');
Route::resource('product' 		 			, ProductController::class)->middleware('cashier');
Route::resource('client' 					, ClientController::class)->middleware('waiter');
Route::resource('user' 						, UserController::class)->middleware('admin');
Route::resource('discount'					, DiscountController::class)->middleware('cashier');

Route::resource('arching' 					, ArchingController::class)->middleware('cashier');
Route::get('arching/print/{id}'				, [ArchingController::class, 'print'])->middleware('cashier');
Route::get('arching/table/{id}'				, [ArchingController::class, 'show_table'])->middleware('cashier');

Route::resource('printer' 					, PrinterController::class)->middleware('cashier');
Route::get('printer/test/{ID}'				, [PrinterController::class, 'test'])->middleware('cashier');

Route::resource('retirement'				, RetirementController::class)->middleware('cashier');
Route::get('retirement/print/{ID}'			, [RetirementController::class, 'print'])->middleware('waiter');
Route::get('retirement/print/arching/{ID}'	, [RetirementController::class, 'print_arching'])->middleware('waiter');

Route::get('notification/query'				, [NotificationController::class, 'query'])->middleware('cashier');
Route::get('notification/all'				, [NotificationController::class, 'all'])->middleware('cashier');
Route::get('notification/read'				, [NotificationController::class, 'read'])->middleware('cashier');
Route::resource('notification'				, NotificationController::class)->middleware('cashier');

Route::post('search' 			 			, [FixedController::class, 'search'])->middleware('waiter');
Route::get('account'      					, [HomeController::class, 'account'])->middleware('waiter');
Route::post('contact'						, [HomeController::class, 'contact']);
Route::post('client/save'					, [ClientController::class, 'save'])->middleware('waiter');
Route::get('product/get/{id}'				, [ProductController::class, 'get'])->middleware('waiter');

Route::resource('fixed'						, FixedController::class)->middleware('admin');
Route::get('fixed/get/{id}'					, [FixedController::class, 'get'])->middleware('waiter');
Route::get('fixed/form/{id}/{type}'			, [FixedController::class, 'form'])->middleware('cashier');
Route::post('fixed/edit/name'				, [FixedController::class, 'edit_name'])->middleware('cashier');

Route::resource('table' 					, TableController::class)->middleware('waiter');
Route::get('table/history/{id}' 			, [TableController::class, 'history'])->middleware('waiter');
Route::get('table/close/{id}'      			, [TableController::class, 'close'])->middleware('cashier');
Route::get('table/charge/{id}'     			, [TableController::class, 'get_charge'])->middleware('cashier');
Route::post('table/charge/{id}'   			, [TableController::class, 'set_charge'])->middleware('cashier');
Route::get('table/print/{id}'      			, [TableController::class, 'print'])->middleware('cashier');
Route::post('table/discount/{id}'      		, [TableController::class, 'discount'])->middleware('cashier');

Route::resource('command' 					, CommandController::class)->middleware('waiter');
Route::get('command/print/{id}'    			, [CommandController::class, 'print'])->middleware('waiter');
Route::get('command/check/{id}' 			, [CommandController::class, 'check'])->middleware('waiter');
Route::post('command/delete/all' 			, [CommandController::class, 'delete_all'])->middleware('waiter');
Route::post('command/observation' 			, [CommandController::class, 'observation'])->middleware('waiter');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'type', 'business_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function business()
    {
        return $this->belongsTo('App\Models\Business');
    }

    public function tables()
    {
        return $this->hasMany('App\Models\Table');
    }

    public function archings()
    {
        return $this->hasMany('App\Models\Arching');
    }

    public function deliveries()
    {
        return $this->hasMany('App\Models\Delivery');
    }

    public function histories()
    {
        return $this->hasMany('App\Models\History');
    }

    public function hours()
    {
        return $this->hasMany('App\Models\Hour');
    }

    public function retirements()
    {
        return $this->hasMany('App\Models\Retirement');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Hour;
use Auth;
use Hash;

class UserController extends Controller
{

    private $path = 'admin.user.';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = Auth::user()->business->users->where('status', '!=', 'deleted');

        return view($this->path.'index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->path.'create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $old = User::where('email', $request->email."@".strtolower(Auth::user()->business->name))->first();

        if($old != null)
        {
            Session(['error' => "El email \"".$request->email."@".strtolower(Auth::user()->business->name)."\" ya existe, ingrese otro y pruebe nuevamente."]);

            return back()->withInput();
        }

        $user               = new User();
        $user->name         = $request->name;
        $user->email        = $request->email."@".strtolower(Auth::user()->business->name);
        $user->password     = Hash::make($request->password);
        $user->color        = $request->color;
        $user->type         = $request->type;
        $user->business_id  = Auth::user()->business_id;
        $user->save();

        $days   = [
            'monday',
            'tuesday',
            'wednesday',
            'thursday',
            'friday',
            'saturday',
            'sunday'
        ];

        if($request->hour == 'null')
        {
            foreach($days as $day_name)
            {
                $status     = $request[$day_name."_selector"] == "on" ? "checked" : "null";

                $hour               = new Hour();
                $hour->hour_start   = $request[$day_name."_start"];
                $hour->hour_end     = $request[$day_name."_end"];
                $hour->user_id      = $user->id;
                $hour->business_id  = $user->business->id;
                $hour->day          = $day_name;
                $hour->status       = $status;
                $hour->save();
            }

        }else
        {
            foreach($days as $day_name)
            {
                $old = User::find($request->hour)->hours->where('day', $day_name)->first();

                $hour               = new Hour();
                $hour               = $old->replicate();
                $hour->user_id      = $user->id;
                $hour->save();
            }
        }

        Session(['success' => "Se creo el usuario \"".$user->name."\""]);

        return redirect('user');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view($this->path."edit", compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user               = User::findOrFail($id);
        $user->name         = $request->name;
        
        if($request->password != null)
            $user->password     = Hash::make($request->password);

        $user->color        = $request->color;
        $user->type         = $request->type;
        $user->save();
        
        $days   = [
            'monday',
            'tuesday',
            'wednesday',
            'thursday',
            'friday',
            'saturday',
            'sunday'
        ];

        if($request->hour == 'none')
        {
            foreach($days as $day_name)
            {
                $status     = $request[$day_name."_selector"] == "on" ? "checked" : "null";

                $hour               = $user->hours->where('day', $day_name)->first();
                $hour->hour_start   = $request[$day_name."_start"];
                $hour->hour_end     = $request[$day_name."_end"];
                $hour->user_id      = $user->id;
                $hour->business_id  = $user->business->id;
                $hour->day          = $day_name;
                $hour->status       = $status;
                $hour->save();
            }
            
        }else
        {
            foreach($days as $day_name)
            {
                $old = User::find($request->hour)->hours->where('day', $day_name)->first();

                $hour               = $user->hours->where('day', $day_name)->first();
                $hour               = $old->replicate();
                $hour->user_id      = $user->id;
                $hour->save();
            }
        }

        Session(['success' => "Se modifico el usuario \"".$user->name."\""]);

        return redirect('user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->hours()->delete();
        $user->delete();

        Session(['success' => "Se elimino el usuario \"".$user->name."\""]);

        return redirect('user');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.dashboard')

@section('title')
	@lang('message.users')
@endsection

@section('content')

<div class="row">
	<div class="col-xs-12">
      	<div class="x_panel">
        	<div class="x_title">
          		<div class="row">
                <div class="col-xs-6">
                  <h4>@lang('message.users_create')</h4>
                  <div class="clearfix"></div>
                </div>
                <div class="col-xs-6 text-right">
                  <a href="{{url('user')}}" class="btn btn-default">
                    <i class="fa fa-chevron-left"></i>
                    @lang('message.back')
                  </a>  
                </div>
              </div>
        	</div>
        	<div class="x_content">
          		<form action="{{url('user')}}" method="POST" class="form-horizontal col-xs-12 col-md-8 col-md-offset-2">
          			@csrf
                @include('helpers.alert')
          			<div class="row">
                  <div class="col-xs-12 col-md-6">
                      <div class="form-group">
                        <label for="">@lang('message.name')</label>
                        <input type="text" id="name" name="name" class="form-control" value="{{old('name')}}" autofocus="" required="">
                      </div>
                  </div>
                  <div class="col-xs-12 col-md-6">
                    <div class="form-group">
                      <label for="">@lang('message.color')</label>
                      <input type="color" name="color" value="#45e8e5" class="form-control">
                    </div>
                  </div>
                </div>
          			<div class="row">
                  <div class="col-xs-12 col-md-6">
                    <div class="form-group">
                      <label for="">@lang('message.user') </label> <small>@lang('message.user_comment')</small>
                      <div class="row">
                        <div class="col-xs-6">
                          <input type="text" name="email" id="email" value="{{old('email')}}" class="form-control" required="">
                        </div>
                        <div class="col-xs-6">
                          <h4><b>@ {{strtolower(Auth::user()->business->name)}}</b></h4>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-xs-12 col-md-6">
                    <div class="form-group">
                      <label for="">@lang('message.password')</label>
                      <input type="password" name="password" class="form-control" required="">
                    </div>
                  </div>
                </div>
          			<div class="row">
                  <div class="col-xs-12 col-md-6">
                    <div class="form-group">
                      <label for="">@lang('message.type')</label>
                      <select name="type" class="form-control">
                        @if(Auth::user()->type == "admin")
                          <option value="admin">Administrador</option>
                        @endif
                        <option value="cashier">Cajero</option>
                        <option value="waiter">Mozo</option>
                      </select>
                    </div>
                  </div>
                  <div class="col-xs-12 col-md-6">
                    <div class="form-group">
                      <label for="">@lang('message.copy_hours')</label>
                      <select name="hour" class="form-control">
                        <option value="null" selected="">Ninguno</option>
                        @foreach(Auth::user()->business->users as $user)
                          <option value="{{$user->id}}">{{$user->name}}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-xs-12">
                    <p>@lang('message.user_hours')</p>
                    <div class="table table-responsive">
                      <table class="table table-striped">
                        <tr>
                          <th>@lang('message.day')</th>
                          <th>@lang('message.hour_start')</th>
                          <th>@lang('message.hour_end')</th>
                          <th>@lang('message.activate')</th>
                        </tr>
                        @php 
                          $days   = [
                              'monday',
                              'tuesday',
                              'wednesday',
                              'thursday',
                              'friday',
                              'saturday',
                              'sunday'
                          ];
                        @endphp
                        
                        @foreach($days as $day)
                          <tr>
                            <td>@lang('message.'.$day)</td>
                            <td>
                              @include('helpers.hour_selector', [
                                                'name'    => $day."_start", 
                                                'min'     => "10",
                                                'value'   => "00:00",
                                                'status'  => 'disabled' 
                                                ])
                            </td>
                            <td>
                              @include('helpers.hour_selector', [
                                                'name'    => $day."_end", 
                                                'min'     => "10",
                                                'value'   => "00:00",
                                                'status'  => 'disabled' 
                                                ])
                            </td>
                            <td>
                              @include('helpers.checkbox', [
                                                'name' => $day."_selector", 
                                                'status' => null,
                                                'text' => "Activar"
                                                ])
                            </td>
                          </tr>
                        @endforeach

                      </table>
                    </div>
                  </div>
                </div>
          			<div class="form-group text-right">
          				<button class="btn btn-info">
          					<i class="fa fa-save"></i>
          					@lang('message.save')
          				</button>
          			</div>
          		</form>
          	</div>
          	<div class="x_footer">
          		<div class="col-xs-6">
          			
          		</div>
          	</div>
        </div>
  	</div>
</div>
@endsection

@section('scripts')
	<script>
		$('#email').keyup(function(tecla) 
		{
      $('#email').val($(this).val().toLowerCase().replace(/\s/g, "-").replace(/[^ a-z0-9áéíóúüñ]+/ig,"-"));
    });

    @foreach($days as $day)
      $('#{{$day}}_selector').on('change',function()
      { 

        if($(this).is(':checked'))
        {
          $('#{{$day}}_start').attr('readonly', false);
          $('#{{$day}}_end').attr('readonly', false);
        }else
        {
          $('#{{$day}}_start').attr('readonly', true);
          $('#{{$day}}_end').attr('readonly', true);
        }
      });
    @endforeach
	</script>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.dashboard')

@section('title')
	@lang('message.users')
@endsection

@section('content')

<div class="row">
	<div class="col-xs-12">
      	<div class="x_panel">
        	<div class="x_title">
        		<div class="row">
        			<div class="col-xs-6">
		          		<h4>@lang('message.users')</h4>
		          		<div class="clearfix"></div>
        			</div>
        			<div class="col-xs-6 text-right">
        				<a href="{{url('admin')}}" class="btn btn-default">
	          				<i class="fa fa-chevron-left"></i>
	          				@lang('message.back')
	          			</a>
        			</div>
        		</div>
        	</div>
        	<div class="x_content">
        		@include('helpers.alert')
          		<div class="table-responsive">
          			<table class="table table-striped">
          				<th>@lang('message.name')</th>
          				<th>@lang('message.user')</th>
          				<th>@lang('message.type')</th>
          				<th>@lang('message.color')</th>
          				<th>@lang('message.edit')</th>
          				<th>@lang('message.delete')</th>
          				
          				@foreach($users as $user)
							<tr>
								<td>{{$user->name}}</td>
								<td>{{$user->email}}</td>
								<td>
									@if($user->type == "admin")
										Administrador
									@elseif($user->type == "cashier")
										Cajero
									@elseif($user->type == "waiter")
										Mozo
									@endif
								</td>
								<td>
									<div style="height: 30px; width: 50%; background:{{$user->color}}; border-radius: 4px;"></div>
								</td>
								<td>
									<a href="{{route('user.edit', $user->id)}}" class="btn btn-primary">
										<i class="fa fa-edit"></i>
									</a>
								</td>
								<td>
									@include('helpers.delete', ['id' => $user->id, 'route' => 'user.destroy'])
								</td>
							</tr>
						@endforeach
          			</table>
          		</div>
          	</div>
          	<div class="x_footer">
          		<div class="col-xs-6">
          			
          		</div>
          		<div class="col-xs-6 text-right">
					<a href="{{url('user/create')}}" class="btn btn-info">
						<i class="fa fa-plus"></i>
						@lang('message.create')
					</a>
          		</div>
          	</div>
        </div>
  	</div>
</div>
@endsection